### ISSUE TITLE
Turn sessionKeepAliveUrl into a public variable instead of a private

### ISSUE THREAD

**Issue by Connor9220** [JillElaine/jquery-idleTimeout#15]
the KeepAliveUrl needs to be a public variable.   It hits the same page.. which can be large or small (load wise) depending on what it is.. can we specify a specific keepalive URL which can be a simple url just to keep the session alive.

**Comment by JillElaine** [comment]
The session keep-alive URL variable has now been moved into the public configuration variables.

Thank you for your feedback.
