### ISSUE TITLE
Time remainig over and not redirect:  setTimeout changed to setInterval 

### ISSUE THREAD

**Issue by marcellobrazil** [JillElaine/jquery-idleTimeout#17]
startDialogTimer = function () {
        dialogTimer = setInterval(function () {checkDialogTimeout();}, (currentConfig.idleCheckHeartbeat * 1000));
    };

    stopDialogTimer = function () {
        clearInterval(dialogTimer);
        clearInterval(remainingTimer);
    };

**Comment by JillElaine** [comment]
Bad bug on my part. Thank you for catching this. It is now fixed.

**Comment by marcellobrazil** [comment]
Welcame Jill.
