### ISSUE TITLE
More configuration variables

### ISSUE THREAD

**Issue by Frankwin** [JillElaine/jquery-idleTimeout#19]
It would be nice to have a couple more configuration variables such as:
- element to center the pop-up window on
- option to have rounded corners on the pop-up (would fit better in our design)
- various color options: title bar, pop-up background, font color (type and size would be great too)

**Comment by JillElaine** [comment]
You may change the position of the dialog box by adding the 'position' option to the function that creates the dialog box. I am unlikely to modify the code to add 'position' as it adds unnecessary complexity, in my opinion.

In the unminified code, edit the .js file, section starting with 
//----------- WARNING DIALOG FUNCTIONS --------------//

    openWarningDialog = function () {

      var dialogContent = "<div id='idletimer_warning_dialog'><p>" + currentConfig.dialogText + "</p><p style='display:inline'>" + currentConfig.dialogTimeRemaining + ": <div style='display:inline' id='countdownDisplay'></div></p></div>";

      $(dialogContent).dialog({
        // add 'position' option
        position: { my: 'center', at: 'center', of: window },  // default value
        buttons: [{
          text: currentConfig.dialogStayLoggedInButton,
    ...

More information on the dialog 'position' option:
https://api.jqueryui.com/dialog/#option-position
https://api.jqueryui.com/position/

Your other requests are for 'styling' of the dialog, which is not included with the plugin.  You can create your own custom CSS for jquery ui or use one of the ready-made themes from the Gallery. The themes will include styling for the dialog box. Please see this site: http://jqueryui.com/themeroller/

Note that rounded corners of the dialog box does not work in Internet Explorer 7 & 8.

I hope this I have understood your request correctly. Please let me know. Thank you.

**Comment by Frankwin** [comment]
Awesome. Thank you.

On Tue, Jul 21, 2015 at 2:26 PM JillElaine <notifications@github.com> wrote:

> You may change the position of the dialog box by adding the 'position'
> option to the function that creates the dialog box. I am unlikely to modify
> the code to add 'position' as it adds unnecessary complexity, in my opinion.
>
> In the unminified code, edit the .js file, section starting with
> //----------- WARNING DIALOG FUNCTIONS --------------//
>
> openWarningDialog = function () {
>
>   var dialogContent = "<div id='idletimer_warning_dialog'><p>" + currentConfig.dialogText + "</p><p style='display:inline'>" + currentConfig.dialogTimeRemaining + ": <div style='display:inline' id='countdownDisplay'></div></p></div>";
>
>   $(dialogContent).dialog({
>     // add 'position' option
>     position: { my: 'center', at: 'center', of: window },  // default value
>     buttons: [{
>       text: currentConfig.dialogStayLoggedInButton,
> ...
>
> More information on the dialog 'position' option:
> https://api.jqueryui.com/dialog/#option-position
> https://api.jqueryui.com/position/
>
> Your other requests are for 'styling' of the dialog, which is not included
> with the plugin. You can create your own custom CSS for jquery ui or use
> one of the ready-made themes from the Gallery. The themes will include
> styling for the dialog box. Please see this site:
> http://jqueryui.com/themeroller/
>
> Note that rounded corners of the dialog box does not work in Internet
> Explorer 7 & 8.
>
> I hope this I have understood your request correctly. Please let me know.
> Thank you.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JillElaine/jquery-idleTimeout/issues/19#issuecomment-123468279>
> .
>
-- 
Best Regards,

Frankwin Hooglander

**Comment by JillElaine** [comment]
Closing issue.
