### ISSUE TITLE
Session Time out dialog box dosen't disappear

### ISSUE THREAD

**Issue by joshiamit24** [JillElaine/jquery-idleTimeout#23]
Session Time out dialog box doesn't disappear when explicitly clicked on Logout button and count shows NAN after 0.

**Comment by JillElaine** [comment]
What is the value of your 'redirectUrl' variable?

**Comment by joshiamit24** [comment]
Logout page URL of my application.
I have three master pages and instead of adding script on all pages. I have created separate JS file and included script in JS file. Then I gave reference of this JS file in Master page.
I have given reference of Jquery Idle time out script and store.Js in master page.
ThanksAmit Joshi 

Date: Mon, 4 Jan 2016 18:51:36 -0800

**Comment by joshiamit24** [comment]
![image](https://cloud.githubusercontent.com/assets/8158164/12119932/8acdbbf0-b39c-11e5-9224-88e7a73c746b.png)

**Comment by joshiamit24** [comment]
When Click on Logout now it is not redirecting. I have added script on master page under document.load.

**Comment by JillElaine** [comment]
Please replace the jquery-idleTimeout script with the jquery-idleTimeout-for-testing.js on your site, and watch the console debug log. One way to do this is to use Mozilla Firefox with the Firebug web developer add-on: http://getfirebug.com/  The console log should tell you exactly where the script is failing. Is it possible that your configuration script in (document).ready is not available on all pages?

**Comment by joshiamit24** [comment]
I don't want to put this script on all pages. I have created separate Js file. But I will check with testing.js file.

**Comment by joshiamit24** [comment]
Logout page has master page reference. on Master page on document.load I have idleTimeout script. so Logout page page_load method is getting called again and again.

**Comment by JillElaine** [comment]
Understood. What I meant was, "Is it possible that your configuration script in (document).ready is not available on all pages *where you need it to be available*?"

**Comment by JillElaine** [comment]
Sounds like you have loaded the script multiple times? It should be loaded only once.

**Comment by joshiamit24** [comment]
Yes because I have three master pages and some of the page don't have master page reference. so I have to add  the script on that page as well.

**Comment by JillElaine** [comment]
Check on each page that the script is loaded only once. The firebug add-on will show the loaded scripts for each page.

**Comment by joshiamit24** [comment]
0:2- NAN value in dialog box shows because of this?

**Comment by JillElaine** [comment]
Yes, the dialog box would normally not be shown when the page properly redirected. The countdownDisplay function just continues counting down as long as the script is still loaded. Typically the idleTimeout script would be unloaded on the redirect page, since the user was logged out. 

If there was a case where someone wanted the dialog box to remain visible and not have the page redirect, then they could rewrite the countdownDisplay function to display "0" and exit that function once zero had been reached. One would also want to unload the idleTimeout script in that case.

**Comment by joshiamit24** [comment]
But in my case Logout page page_load event is getting called multiple times and it is not getting redirected.

**Comment by JillElaine** [comment]
Yes, you need to change your page so that the idleTimeout script is loaded only once. It should not be called multiple times. This is a problem with your site, not a problem with the idleTimeout script. I am not sure how to help you with the set up of your site and how you load your scripts.

**Comment by joshiamit24** [comment]
My issue is resolved. Thanks for your help.

**Comment by joshiamit24** [comment]
one question. This ideal time script internally uses local storage to store time?

**Comment by JillElaine** [comment]
If you read the heavily commented code in jquery-idleTimeout-for-testing.js, you can learn much of the functionality. Basically, the idleTimeout script uses local storage (via Marcus Westin's store.js) to store the current time of the last detected activity (eg: mouse move) in the variable, idleTimerLastActivity. See below. 

Local storage is also used to store the value of other variables that need to be shared among windows and tabs.

```
    startIdleTimer = function () {
      console.log('start startIdleTimer');
      stopIdleTimer();
      store.set('idleTimerLastActivity', $.now());  // this is the reference to local storage
      checkIdleTimeoutLoop();
    };
```

**Comment by JillElaine** [comment]
User configuration issue. Resolved.
