### ISSUE TITLE
iframe inactivity detection bug

### ISSUE THREAD

**Issue by a-espitia** [JillElaine/jquery-idleTimeout#34]
in the demo, if you just scroll one of the iframes up and down and don't do anything else on the page, the idle time does not pick that up as an activity, and the logout dialog will trigger.  

http://jillelaine.github.io/jquery-idleTimeout/iframe-demo.html

my scenario is that i have an iframe, with a PDF or HTML inside of it, that requires a lot of reading.  so, just scrolling up and down on the iframe should be detected as activity on the page, and not cause the timeout.

**Comment by JillElaine** [comment]
Which activity to detect is configurable. On my I-frame demo page, it notes: "Activity events detected, as configured by the idle-Timeout setup on this demonstration page, are CLICKS AND KEYPRESSES ONLY." 

So you are correct that 'scrolling' is NOT detected on the demo page.

If you install the I-frame idleTimeout script on YOUR page, you may configure it to detect whatever activity you want. Please read about activityEvents variable: the https://github.com/JillElaine/jquery-idleTimeout/wiki/Public-Configuration-Variables

**Comment by a-espitia** [comment]
Thank you, i confirmed that it does work with teh right configuration.  i assumed it was the same configuration as the non-iframe demo, since that one does respond to scrolling.
