### ISSUE TITLE
session expires when mouse moving

### ISSUE THREAD

**Issue by Sajith-vr** [JillElaine/jquery-idleTimeout#45]
I am facing an issue with session timeout when i am moving mouse

**Comment by JillElaine** [comment]
Please answer these questions. What is your plugin configuration? Which web browser do you use? Are you using a mobile device (tablet, phone) or a computer? Is your mouse cursor moving within a 'non-domain' i-frame when the session expires?

**Comment by Sajith-vr** [comment]
version 1.0.10,
I used google crome browser in a computer(both linux and windows),

**Comment by JillElaine** [comment]
Two questions to answer:
1. What is your 'document ready' function? Please copy and paste your entire 'document ready' function with **"insert code"** markup . This is your plugin configuration. See example below. 
```
$(document).ready(function () {
    $(document).idleTimeout({
      redirectUrl:  '/logout' // redirect to this url. Set this value to YOUR site's logout page.
    });
  });
```
2. Do you have 'non domain' i-frames within your pages? If yes, mouse movements will NOT be detected within 'non domain' i-frames. For more i-frame information, see https://github.com/JillElaine/jquery-idleTimeout/wiki/Iframes---Information-&-Troubleshooting

**Comment by Sajith-vr** [comment]
$(document).ready(function () {
   $(document).idleTimeout({
      redirectUrl: '<?php echo base_url(); ?><?php echo $url;?>', //
redirect to this url
      idleTimeLimit: 300, //300- 15 seconds
      activityEvents: 'click keypress scroll wheel mousewheel', // separate
each event with a space
      dialogDisplayLimit: 30, // Time to display the warning dialog before
logout (and optional callback) in seconds
      sessionKeepAliveTimer: false // Set to false to disable pings.
    });
      });

**Comment by Sajith-vr** [comment]
there is no iframes used in any of pages

**Comment by JillElaine** [comment]
Sajith-vr, your 'document ready' overrides the default '**activityEvents**' variable and does **NOT** include 'mousemove'. If you want to detect mouse movement, you must include '**mousemove**'...OR else do not override the default 'activityEvents' variable: it includes 'mousemove' by default.

Please read about the public configuration variables on this page. https://github.com/JillElaine/jquery-idleTimeout/wiki/Public-Configuration-Variables

**Comment by Sajith-vr** [comment]
Ok thank you
