### ISSUE TITLE
Releasing jquery-idleTimeout under MIT license 

### ISSUE THREAD

**Issue by abmathur3177** [JillElaine/jquery-idleTimeout#47]
Hello Jill - This is Abhishek Mathur from IBM. We found your jquery-idleTimeout work excellent for our use, where we were struggling to get the idletimeout support for iframes. Your library has done the job for us. We would like to distribute this as part of our application. But for that, we need the license to be released under MIT license clause. That is IBM's guidelines. 
Is that possible at all? 

It is really urgent for us as we have a a couple of critical issues dependent on the usage of this library. Request you to respond and if possible release this under MIT license. 

Thanks
Abhishek Mathur  (abmathur@gmail.com)

**Comment by JillElaine** [comment]
Hello Abhishek - Glad this code is working for you. My code is a fork of https://github.com/josebalius/jquery-idleTimeout

That fork was a fork of https://github.com/philpalmieri/jquery-idleTimeout which is where the "Creative Commons Attribution-Share Alike 3.0" license was first attached in May, 2012.

There are other programmers involved with both of those forks via pull requests.

My understanding of license modification of forked code is: 1) All code that is unmodified should remain under the original license unless permission to modify the license can be obtained from the original author of that code.

2) New code that a person writes, including new code in a fork, can be licensed however the author desires.

My sources for this information: http://programmers.stackexchange.com/questions/222362/if-i-fork-an-open-source-project-and-make-improvements-in-the-fork-will-it-or-i

http://programmers.stackexchange.com/questions/188712/ethics-and-best-practices-when-forking-code-base

http://programmers.stackexchange.com/questions/277688/if-i-fork-a-project-on-github-that-is-licensed-under-mit-how-to-i-handle-the-at

https://github.com/blog/1530-choosing-an-open-source-license

The next question is: what qualifies as 'modified' code? If you compare my scripts with philpalmieri's scripts, there are only a few common lines. If you compare my scripts with josebalius' scripts, there are many more common lines, but the 2 most recent versions of josebalius' scripts are actually older versions of my scripts as he responded to my pull requests.

https://github.com/josebalius/jquery-idleTimeout/pulls?q=is%3Apr+is%3Aclosed

The most recent version of josebalius' script that he authored is from Jul 28, 2013.
https://github.com/josebalius/jquery-idleTimeout/commits/7ce9af878be33b20f681bb7d4d043ff65ae536cf

To further complicate the issue, I have merged 2 pull requests from svenbit back in Nov 2014. https://github.com/JillElaine/jquery-idleTimeout/pulls?q=is%3Apr+is%3Aclosed

I think my scripts are almost complete rewrites of josebalius's last authored script. And I wrote all of the iframe portion of my jquery-idleTimeout.

So--> you have my permission to modify the license on code that I authored on your fork of my jquery-idleTimeout. I cannot, of course, give you permission to modify licensing on code I did not write.

I appreciate being given an attribution for the code that I authored.

Please let me know if you have any further questions, or if you need more formal documentation to change the licensing on my portion of the code.

**Comment by abmathur3177** [comment]
Thank you Jill for such a quick and prompt response. I really do appreciate it. I will run your response through my legal team here at IBM. The good part is, we are using a fork off your codebase which it seems is almost a rewrite from the original codebase. With your permission here, it seems like we can use the code. But if legal here insist, would you be able to change your code to be released under MIT licensing terms? I am naive to this, so you can correct me if this is absolutely not possible. 
We are specifically interested in the iframe portion of the jquery-idleTimeout - which is where our customers are seeing issues in our application. 

Thanks
Abhishek Mathur

**Comment by JillElaine** [comment]
Okay. Let me know if you need anything further from me. Thank you. Jill Elaine

**Comment by abmathur3177** [comment]
Hello Jill, 
Lawyers and IP attorneys at IBM have come back with some more comments. Unfortunately, they are saying that the license under which this library is currently released - Create Commons Share-Alike (CC-BY-SA) - cannot be used in combination with IBM license. 
Their strong recommendation and preference is that the license for jquery-IdleTimeout be released under MIT license. This is needed, because while you have been gracious enough to say that we can use the library, you are not able to give us the rights of parts of "jquery-idleTimeout" that you did not author. And the lawyers cannot understand which part you authored versus what is original. 
Therefore the request is - if you can release the code under MIT license. 

Or, as you stated earlier that you are willing to provide "more formal documentation to change the licensing on [her] portion of the code," - they wanted to know what that formal documentation would entail. 

Can you please assist and respond to this? I really appreciate you helping here. 
Most ideal would be to release this under MIT license. 

Thanks
Abhishek Mathur

**Comment by JillElaine** [comment]
What if I create a new file with only the iframe portion of the code and release it under the MIT license? This "iframe functions only" code would not be a complete, 'stand-alone' plugin, but the MIT license on it would allow you to incorporate the iframe code into your fork of the jquery-idleTimeout plugin.

**Comment by abmathur3177** [comment]
Hello Jill,
Thanks again for the response. From your list of files, IBM is primarily interested in the following js file only - jquery-idleTimeout-iframes.js . So Yes, ideally if you can simply release this file under the MIT license it would help to incorporate the iframe code into our existing jquery-idleTimeout plugin. 

Thanks
Abhishek Mathur.

**Comment by JillElaine** [comment]
Hello Abhishek, I'm sorry I am unable to accommodate your request. As you know, I can't "simply release" a file under a different license if it contains code I did not author. I am unwilling to attempt to obtain permission to change the license from the several potential authors whose code may be contained within my forks of their projects. I have withdrawn my earlier permissions and offers related to your request. Again, my apologies.
