### ISSUE TITLE
How much of jquery-ui do you need to bundle?

### ISSUE THREAD

**Issue by L5eoneill** [JillElaine/jquery-idleTimeout#52]
Documentation doesn't state how much of jQuery UI is needed. Assuming one wants the basic out-of-the-box functionality as in the demo:

- Is Theme css required?
- Any Effects?
- Any Interactions?
- Which Widgets, if any?

This affects what bundle a user creates when downloading a package from jQuery UI

**Comment by pierre-alain-b** [comment]
For information, it is pretty easy not to depend on jquery-ui.
In my case, I replaced the dependency to jquery-ui to a dependency to bootbox to display the prompt!

**Comment by pierre-alain-b** [comment]
I propose to close this issue ;-)

**Comment by JillElaine** [comment]
Thank you. Closing issue now.
