### ISSUE TITLE
Uncaught TypeError: $(...).idleTimeout is not a function

### ISSUE THREAD

**Issue by nitinpatil14** [JillElaine/jquery-idleTimeout#53]
I have loaded all 3 necessary js file and trying  to implement timeout functionality in my project. i have wrote the program in header.jsp file as i need this function every where. but it is giving me above error. plus when i run the same functionality in individual jsp page, its working fine.

**Comment by JillElaine** [comment]
Your error, "is not a function", means the idleTimeout function has not been properly loaded on your page. Please test your pages with the idleTimeout-for-testing script, jquery-idleTimeout-for-testing.js, and watch the console to identify the problem. More information is here: https://github.com/JillElaine/jquery-idleTimeout/wiki/General-Troubleshooting
