### ISSUE TITLE
store.js

### ISSUE THREAD

**Issue by loginetsolutions** [JillElaine/jquery-idleTimeout#54]
Hello,

This is not really an issue but a question. I didn't find any other means to contact you.
I want to implement your script but I have to download the store.js dependency.
Since 5 years ago the store.js changed and I don't find the right file to include with your script.
the store.min.js is not existing anymore. It is changed to store.everything.min.js which include other js files... please advise.
Thanks for your help

**Comment by JillElaine** [comment]
This script has not been updated for 5 years, so it's possible it does not work correctly on all browsers and platforms. I caution anyone considering using this script to first explore updated options. Technology moves on!

To address your issue, the idletimeout script calls for store.js "version 1.3.4 or newer". You can find older versions of the store.js script. Go to the store.js page: https://github.com/marcuswestin/store.js. Click the 'button' that says "Branch: master". You will see "Branches" and "Tags" in the dropdown menu. Click "Tags" and then scroll to the version of store.js you want. 

I would recommend trying newer versions of store.js with the idletimeout script to see if they work compatibly. But here is a direct link to store.js version 1.3.4: https://github.com/marcuswestin/store.js/tree/v1.3.4 - Note that this store.js is 8 years old. Advice is to use the "Tag" button on that page to try a newer version. 

Best of luck!

**Comment by pierre-alain-b** [comment]
It works pretty well with the latest store.js in my experience!

@JillElaine your idleTimeout plugin works very well for me, I've just replaced Jquery UI with Bootbox (fresher) but the core does the job very well. Would you recommend a fresher alternative for idleTimeout?

**Comment by JillElaine** [comment]
@pierre-alain-b thanks for testing the latest version of store.js with the idletimeout plugin. It's good to hear it still works. I feel bad that the plugin is neglected and needs updating. Perhaps you would like to adopt it? There is a way to transfer ownership in github. I tried hard to properly document the plugin so that its workings could be understood. What do you think?

**Comment by pierre-alain-b** [comment]
I totally agree the documentation of the code is just GREAT! this makes the use of it very simple and trustworthy.
I have already quite a number of engagements and you know, and only 24h a day, tech has not improved this :-/ now I am using it in a production environment with hundreds of users so it could make sense to ensure this component is not derelict. Let me think about it, I know handling a plugin can take a lot of time to be well done!

**Comment by pierre-alain-b** [comment]
btw, I think this issue can be closed :-)

**Comment by JillElaine** [comment]
There is at least one patch/pull request that need to be rolled in, solves issue #18 . I had this plugin running on a big site with about 100 users w/o a problem, but not sure how well it works with all the latest browsers. Ping me, @pierre-alain-b if you want to adopt this. :-) Thank you.Closing issue now.
